---
title: ''
author: "Matthew R.V. Ross"
email: matt.ross@colostate.edu
output:
  pdf_document:
    latex_engine: pdflatex
    template: rap-latex-cv.tex
  word_document: default
  html_document:
    df_print: paged
fontfamily: palatino
fontsize: 10pt
geometry: margin=1in
github: matthewross07
jobtitle: Assistant Professor of Water Quality, Colorado State University
linkcolor: blue
orcid: http://orcid.org/0000-0001-9105-4255
fontawesome: yes
address: 1476 Campus Delivery, Fort Collins, CO 80523
updated: yes
urlcolor: blue
web: matthewrvross.com
---

<!-- Comments from committee 1) Ask for a person to come do an
assessment, 2) In-kind contributions are useful and I should brag about
it. 3) Keep on top of that kind . 4) Formatting and bold your name. 5)
highlight students with * etc... 6) Student work. 7) Advisees highlight
8. Sustaining colorado watersheds October in Avon. 9. Ed Harvey and Mike
Martin WQ expertise parks. -->



# Education

*Duke University*, Ph.D. Ecology \hfill 2017

*University of Colorado at Boulder*, B.A. Ecology and Evolutionary Biology with a Minor in French \hfill 2010

# Employment

*Colorado State University Department of Ecosystem Science and Sustainability*

 > Assistant Professor of water quality \hfill 2018--present

*University of North Carolina at Chapel Hill*

 > Post-doctoral researcher in the Global Hydrology Lab with Tamlin Pavelsky \hfill 2017--2018


# Publications

## **2019**

**MRV Ross**, S Topp, AP Appling, C Kuhn, D Butman, M Simard, T Pavelsky. *AquaSat: a dataset to enable remote sensing of water quality for inland waters*. Water Resources Research. 
2019. DOI: [10.1029/2019WR024883](https://doi.org/10.1029/2019WR024883)

## **2018**

Barger, N. N., Gardner, T. A., Sankaran, M., Belnap, J., Broadhurst, L., Brochier, V., 
Isbell, F., Meyfroidt, P., Moreira, F., Nieminen, T. M., Okuro, T., Rodrgiues, R. R., Saxena, V., and **Ross, M**. *Chapter 3: Direct and indirect drivers of land degradation and restoration*. In IPBES (2018): The IPBES assessment report on land degradation and restoration. Montanarella, L., Scholes, R., and Brainich, A. (eds.). Secretariat of the Intergovernmental Science-Policy Platform on 
Biodiversity and Ecosystem Services, Bonn, Germany, pp. 137-218

**MRV Ross**, F Nippgen, BA Hassett, BL McGlynn, ES Bernhardt. *Pyrite oxidation drives exceptionally high weathering rates and geologic $CO_2$ release in mountaintop-mined landscapes*. Global Biogeochemical Cycles. 2018. doi: [10.1029/2017GB005798](https://doi.org/10.1029/2017GB005798)

AA Peri\c{c}ak CJ Thomas, DA Kroodsma, MF Wasson, **MRV Ross**, NE Clinton, DJ Campagna, Y Franklin, ES Bernhardt, JF Amos. *Mapping the yearly extent of surface coal mining in Central Appalachia using Landsat and Google Earth Engine*. PLOS ONE. 2018. doi: [10.1371/journal.pone.0197758](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0197758)

## **2017**

F Nippgen, **MRV Ross**, ES Bernhardt, BL McGlynn. *Creating a more perennial problem? Mountaintop removal coal mining enhances and sustains sailine baseflows of Appalachian watersheds*. Environmental science & technology. 2017. doi: [10.1021/acs.est.7b02288](https://pubs.acs.org/doi/abs/10.1021/acs.est.7b02288)

## **2016**

**MRV Ross**, BL McGlynn, ES Bernhardt. *Deep impact: effects of mountaintop mining on surface topography, bedrock structure, and downstream waters*. 2016. Environmental science & technology. doi: [10.1021/acs.est.5b04532](https://pubs.acs.org/doi/abs/10.1021/acs.est.5b04532)


## **2015**

**MRV Ross**, ES Bernhardt, MW Doyle, JB Heffernan. *Designer ecosystems: incorporating design approaches into applied ecology*. 2015. Annual Reviews of Environment and Resources. doi: [10.1146/annurev-environ-121012-100957](https://doi.org/10.1146/annurev-environ-121012-100957)

MC Arnold, LA Friedrich, TT Lindberg, **MRV Ross**, NM Halden, ES Bernhardt, VP Palace, RT Di Giullio. *Microchemical analysis of selenium in otoliths of two West Virginia fishes captured near mountaintop removal coal mining operations*. 2015. Environmental Toxicology and Chemistry. doi: [10.1002/etc.2885](https://setac.onlinelibrary.wiley.com/doi/abs/10.1002/etc.2885)

## **2012**

**MR Ross**, SC Castle, NN Barger. *Effects of fuels reductions on plant communities and soils in a Pi\~non Juniper woodland*. 2012. Journal of arid environments. doi: [10.1016/j.jaridenv.2011.11.019](https://doi.org/10.1016/j.jaridenv.2011.11.019) 

## Publications in review

AC Brooks, **MRV Ross**, F Nippgen, BL McGlynn, ES Bernhardt. *Mountaintop removal coal mining watersheds export excessive nitrate.*  In revision at Journal of Geophysical Research: 
Biogeosciences

S Topp, T Pavelsky, D Jensen, M Simard, **MRV Ross**. *Remote sensing of water quality: a 50-year review of methods and applications.* In review. 


## Publications in prep (manuscript in internal review)


A Whittermore, **MRV Ross**, X Yang, W Dolan, T Langhorst, T Pavelsky, S Januchowski-Hartley.
*The construction and validation of a citizen science derived Gloval River Obstruction Database (GROD).*

M Simonin, JD Rocca, J Gerson, E Moore, **MRV Ross**, A Brooks, J Craine, L Czaplicki N Fierer ES Bernhardt. *Biodiversity loss across multiple kingdoms of life associated with surface coal mining activities in Central Appalachian rivers.*

K Jaeger, **MRV Ross**. *Process domains in synthetic landscapes: 
uncoupling of geomorphic process and form in
the mountaintop mining region of West Virginia, USA*

# Grants and Awards


## Awarded

## **2019**

NSF DEB Macrosystems and NEON-Enabled Science, CO-PI *Collaborative Research:
MACRO-Sheds: Comparative Ecosystem Biogeochemistry at Continental Scales*
(CSU portion: $420,864)

NSF EAR Hydrological Sciences Post-DOC awarded directly to Anna Bergstrom. 
*Controls on weathering, solute fluxes, and geologic carbon cycling in 
glacierized catchments* Faculty adviser for post-doc ($174,000).

### **2018**

Colorado Water Institute, CO-PI with Ed Hall. *Tools for improving knowledge of reservoir water quality in the Front Range of Colorado* ($49,991) 


**2016**

* Grand Prize AGU/NASA Data Visualization and Storytelling Competition

* Fellow for Intergovernmental Panel on Biodiversity and Ecosystem Assessment

* Finalist for Mozilla Fellowship for Open Science

**2015** 

* Gordon Research Conference Rising Star Award ($2500)

**2013** 

* NSF Graduate Research Fellowship

**2012**

* NSF IGERT for Wireless Intelligent Sensor Networks

# Presentations 

F Nippgen, MRV Ross, ES Bernhardt, BL McGlynn. *Deconstructing the deconstruction of Appalachia: Mountaintop mining effects on hydrology across temporal and spatial scales*. Fall Meeting of the American Geophysical Union, New Orleans, December 2017. 

MRV Ross, F Nippgen, BL McGlynn, ES Bernhardt.*Yesterdays forest, tomorrows savannah? Legacies in the man-made mountains of Appalachia*. Fall Meeting of the American Geophysical Union, New Orleans, December 2017. *Invited

F Nippgen, MRV Ross, ES Bernhardt, BL McGlynn. *Short and long-term effects of a large-scale critical zone disturbance on hydrologic response*, UCOWR, Fort Collins, June 2017

MRV Ross, F Nippgen, BL McGlynn, ES Bernhardt. *Disturb 1% of the land, generate 50% of the regional ion flux*. Society for Freshwater Science, Raleigh, June, 2017.

MRV Ross, F Nippgen, BL McGlynn, ES Bernhardt. *Tracing disturbance impacts on water quantity and quality through a stream network*. European Geophysical Union, Vienna, April, 2017

MRV Ross, F Nippgen, Hassett B., BL McGlynn, ES Bernhardt. *Melting mountains of Appalachia: exceptionally high weathering rates in mined watersheds*, American Geophysical Union Fall Meeting, 2016

Nippgen F., MRV Ross, ES Bernhardt, McGlynn, B.L. *Mountaintop removal mining: from ephemeral to perennial streams*, American Geophysical Union Fall Meeting 2016

Brooks, A.C., MRV Ross, F Nippgen, ES Bernhardt, McGlynn, B.L. *Old mountains, new nutrients: Mountaintop mining's impact on watershed scale nitrogen export*, American Geophysical Union Fall Meeting 2016

MRV Ross, Visualizing complex spatiotemporal data using R and ShinyR. Duke Data+ Seminar Series. July 2016. *Invited

MRV Ross,  F Nippgen, BL McGlynn, ES Bernhardt. *Contaminants in time and space: Mountaintop mining impacts on stream hydrology, biogeochemistry and macroinvertebrates*. Society for Freshwater Sciences, Sacramento, May 2016

MRV Ross, F Nippgen, BL McGlynn, ES Bernhardt. *Geomorphic signals of the Anthropocene: Mountaintop Mining impacts on the  morphology of Central Appalachia*. American Association of Geographers (AAG) Annual Meeting, San Francisco, 2016. 

F Nippgen, MRV Ross, BL McGlynn, ES Bernhardt, *Mountaintop mining effects on watershed hydrology*, American Geophysical Union Fall Meeting 2015 *Invited

MRV Ross, F Nippgen,., BL McGlynn, ES Bernhardt. *When everything changes: Catchment scale biogeochemical impacts of mountaintop mining*. Gordon Research Seminar, Hanover, NH, June, 2015

MRV Ross, F Nippgen,., BL McGlynn, ES Bernhardt. *Watershed scale biogeochemical impacts of mountaintop mining*. Ecological Society of America Meeting, Baltimore, MD August 2015

MRV Ross, ES Bernhardt. *Not just scratching the surface: Estimating the deep impacts of mountaintop mining*. Joint Aquatic Sciences Meeting, Portland, OR, May, 2014. 

MRV Ross, ES Bernhardt, Marani, M. *Controls on soil oxygen by salt marsh plants in the Venice Lagoon*. Duke Wireless Sensor Network IGERT seminar. Durham, NC. October, 2013.  


# Posters

MRV Ross, *Sensing rivers and streams*. Gordon Research Conference, Lewiston, ME, June 2017

KL Jaeger, MRV Ross, *Process domains in synthetic landscapes: slope-area relationships in the mountaintop mining region of central Appalachia*. American Geophysical Union Fall Meeting. San Francisco, CA. (12/2014)


# Other Publications

Grimbert, Pierre., *The Secret of Ji: The Shadow of the Ancients*. Translated by Matt Ross. Amazon Crossing, Seattle, 2014

Grimbert, Pierre., *The Secret of Ji: The Orphan's Promise*. Translated by Matt Ross and Eric Lamb. Amazon Crossing, Seattle, 2013

Grimbert, Pierre., *The Secret of Ji: The Six Heirs*. Translated by Matt Ross and Eric Lamb. Amazon Crossing, Seattle, 2012. 


