---
title: ''
author: "Matthew R.V. Ross"
email: matt.ross(at)colostate.edu
output:
  pdf_document:
    latex_engine: pdflatex
    template: rap-latex-cv.tex
  html_document:
    df_print: paged
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
geometry: margin=1in
github: matthewross07
jobtitle: Assistant Professor of Water Quality
linkcolor: blue
orcid: http://orcid.org/0000-0001-9105-4255
fontawesome: yes
address: NESB B258
updated: yes
urlcolor: blue
web: matthewrvross.com
---

# EDUCATION

*Duke University*, Ph.D. Ecology \hfill 2017

*University of Colorado at Boulder*, B.A. Ecology and Evolutionary Biology with a Minor in French \hfill 2010

# EMPLOYMENT
*Colorado State University Department of Ecosystem Science and Sustainability*

 > Assistant Professor of water quality \hfill 2018--present

*University of North Carolina at Chapel Hill*

 > Post-doctoral researcher in the Global Hydrology Lab with Tamlin Pavelsky \hfill 2017--2018




# PUBLICATIONS

## **Journal Articles**

**MRV Ross**, F Nippgen, BA Hassett, BL McGlynn, ES Bernhardt. *Pyrite oxidation drives exceptionally high weathering rates and geologic $CO_2$ release in mountaintop-mined landscapes*. Global Biogeochemical Cycles. doi: [10.1029/2017GB005798](https://doi.org/10.1029/2017GB005798)

AA Peri$\c{c}ak CJ Thomas, DA Kroodsma, MF Wasson, **MRV Ross**, NE Clinton, DJ Campagna, Y Franklin, ES Bernhardt, JF Amos. *Mapping the yearly extent of surface coal mining in Central Appalachia using Landsat and Google Earth Engine*. PLOS ONE. doi: [10.1371/journal.pone.0197758](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0197758)

MC Arnold, LA Friedrich, TT Lindberg, MRV Ross, NM Halden, ES Bernhardt, VP Palace, RT Di Giullio. *Microchemical analysis of selenium in otoliths of two West Virginia fishes captured near mountaintop removal coal mining operations*. Environmental Toxicology and Chemistry. doi: [10.1002/etc.2885](https://setac.onlinelibrary.wiley.com/doi/abs/10.1002/etc.2885)




# PUBLIC MEDIA

"Nano-seconds" lecture by Grace Hopper. https://www.youtube.com/watch?v=JEpsKnWZrJ8

# TEACHING

*Associate Professor, Mathematics, Vassar* \hfill 1931--1941

> Teach students about math, began career in programming and largely developed design and implementation of a computer compiler.
  
*Director, Navy Programming Languages Group* \hfill 1967--1977

> She developed validation software for COBOL and its compiler as part of a COBOL standardization program for the entire Navy. Hopper advocated for the Defense Department to replace large, centralized systems with networks of small, distributed computers. Any user on any computer node could access common databases located on the network. She developed the implementation of standards for testing computer systems and components, most significantly for early programming languages such as FORTRAN and COBOL. The Navy tests for conformance to these standards led to significant convergence among the programming language dialects of the major computer vendors. In the 1980s, these tests (and their official administration) were assumed by the National Bureau of Standards (NBS), known today as the National Institute of Standards and Technology (NIST). (Source: https://en.wikipedia.org/wiki/Grace_Hopper)
# AWARDS

**1964**  *Society of Women Engineers Achievement Award*, the Society’s highest honor, “In recognition of her significant contributions to the burgeoning computer industry as an engineering manager and originator of automatic programming systems.”

**1969**  *Data Processing Management Association Man of the Year* (now called the Distinguished Information Sciences Award)

**1973** *Distinguished Fellow of the British Computer Society*. First American and the first woman of any nationality to be given award.

**1982** *American Association of University Women Achievement Award*

**1987** *Computer History Museum Fellow Award Recipient* First to receive this award, for contributions to the development of programming languages, for standardization efforts, and for lifelong naval service.

**1991**: *National Medal of Technology*

**1996**: *USS Hopper (DDG-70) was launched*. Nicknamed Amazing Grace, it is on a very short list of U.S. military vessels named after women.

**2009**: The Department of Energy's National Energy Research Scientific Computing Center named its flagship system "Hopper"

**2016**: Posthumously awarded a *Presidential Medal of Freedom* for her accomplishments in the field of computer science

